%%  InitializeUI
%%% InitializeUI
%%% InitializeUI
function Handles=InitializeUI(Opts)

%%% This function sets up the gui and populates several UserData and
%%% ApplicationData properties with data needed by other functions and ui
%%% callbacks, some of which is set in other functions
%%%
%%% MainFigure : UserData contains the application handle list
%%% MainFigure : ApplicationData contains initialization parameters, etc...
%%% MainAxes   : UserData 
%%% MainAxes   : ApplicationData 

global Debug
global Model

fprintf('SSViz++ Setting up GUI ... \n')
if Debug,fprintf('SSViz++ Function = %s\n',ThisFunctionName);end

FontOffset=Opts.FontOffset;
AppName=Opts.AppName;
BoundingBox=Opts.BoundingBox;
DepthContours=Opts.DepthContours;
ColorMap=Opts.ColorMap;
UseGoogleMaps=Opts.UseGoogleMaps;
ForkAxes=Opts.ForkAxes;
HOME=Opts.HOME;
KeepInSync=Opts.KeepScalarsAndVectorsInSync;

panelColor = get(0,'DefaultUicontrolBackgroundColor');

ratio_x=get(0,'ScreenPixelsPerInch')/72;
fs3=floor(get(0,'DefaultAxesFontSize')/ratio_x)+FontOffset;
fs2=fs3+2;
fs1=fs3+4;
fs0=fs3+6;
global Vecs
Vecs='on';

%LeftEdge=.01;

colormaps={'noaa_cmap','jet','hsv','hot','cool','gray'};
cmapidx=find(strcmp(ColorMap,colormaps));

% normalized positions of container panels depend on ForkAxes
if ~ForkAxes
    
    Handles.MainFigure=figure(...
        'Units','normalized',...
        'Color',panelColor,...
        'OuterPosition',[0.05 .2 Opts.AppWidthPercent/100 .877*Opts.AppWidthPercent/100],...
        'ToolBar','figure',...
        'DeleteFcn',@ShutDownUI,...
        'Tag','MainVizAppFigure',...
        'NumberTitle','off',...
        'Name',AppName,...
        'Resize','off');
        Handles.panHandle=pan(Handles.MainFigure); %#ok<*NASGU>
        Handles.zoomHandle=zoom(Handles.MainFigure);
        
    Positions.CenterContainerUpper      = [.50 .45 .24 .54];
    Positions.CenterContainerMiddle     = [.50 .21 .12 .23];
    Positions.CenterContainerLowerLeft  = [.50 .10 .12 .11];
    Positions.CenterContainerLowerRight = [.63 .10 .12 .11];
    Positions.FarRightContainer         = [.75 .10 .24 .79];
    Positions.LogoContainer             = [.75 .90 .24 .09];
    Positions.StatusUrlBarContainer     = [.50 .01 .49 .09];
                   
else
    
    Handles.MainFigure=figure(...
        'Units','normalized',...
        'Color',panelColor,...
        'OuterPosition',[0.52 .2 .45 .79],...
        'ToolBar','figure',...
        'DeleteFcn',@ShutDownUI,...
        'Tag','MainVizAppFigure',...
        'NumberTitle','off',...
        'Name',AppName,...
        'Resize','off');
    

    Handles.MainFigureSub=figure(...  % this contains the drawing axes if forked
        'Units','normalized',...
        'Color',panelColor,...
        'OuterPosition',[0.05 .2 .9 .8],...
        'ToolBar','figure',...
        'DeleteFcn','',...
        'Tag','MainVizAppFigureSub',...
        'NumberTitle','off',...
        'Name',AppName,...
        'CloseRequestFcn','');
    
    Handles.panHandle=pan(Handles.MainFigureSub);
    Handles.zoomHandle=zoom(Handles.MainFigureSub);
    
    Positions.CenterContainerUpper       = [.01 .45 .48 .54];
    Positions.CenterContainerMiddle      = [.01 .21 .48 .23];
    Positions.CenterContainerLowerLeft   = [.01 .10 .48 .11];
    Positions.CenterContainerLowerRight  = [.01 .10 .48 .11];
    Positions.FarRightContainer          = [.50 .10 .48 .79];
    Positions.LogoContainer              = [.50 .90 .48 .09];
    Positions.StatusUrlBarContainer      = [.01 .01 .98 .09];
    
end

Handles=SetPanZoomFxns(Handles);

% 
% set(Handles.panHandle,'ActionPostCallback',@RecordAxisLimits);
% set(Handles.zoomHandle,'ActionPostCallback',@RecordAxisLimits);

setappdata(Handles.MainFigure,'FontSizes',[fs0 fs1 fs2 fs3]);

%% containers for figure content
%%%%%%%%
% StatusUrlBar Container
% StatusUrlBar Container
%%%%%%%%
StatusUrlBarContainer = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Position',Positions.StatusUrlBarContainer);

%%%%%%%%
% MainAxes Container
% MainAxes Container
%%%%%%%%
if ~ForkAxes
    MainAxesPanel = uipanel(...
        'Parent',Handles.MainFigure,...
        'BorderType','etchedin',...
        'BackgroundColor',panelColor,...
        'Units','normalized',...
        'Position',[.01 .01 .49 .98]);
else
    MainAxesPanel = uipanel(...
        'Parent',Handles.MainFigureSub,...
        'BorderType','etchedin',...
        'BackgroundColor',panelColor,...
        'Units','normalized',...
        'Position',[.01 .01 .98 .98]);
end

%%%%%%%%
% Center Container Upper
% Center Container Upper
%%%%%%%%
Handles.CenterContainerUpper = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'HitTest','off',...
    'Position',Positions.CenterContainerUpper);

%%%%%%%%
% Center Container Middle
% Center Container Middle
%%%%%%%%
Handles.CenterContainerMiddle = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','beveledin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Title','Background Maps',...
    'FontSize',fs0,...
    'HitTest','off',...
    'Position',Positions.CenterContainerMiddle);

%%%%%%%%
% Center Container Lower Left
% Center Container Lower Left
%%%%%%%%
Handles.CenterContainerLowerLeft = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','beveledin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Title','Print',...
    'FontSize',fs0,...
    'HitTest','off',...
    'Position',Positions.CenterContainerLowerLeft);

%%%%%%%%
% Center Container Lower Right
% Center Container Lower Right
%%%%%%%%
Handles.CenterContainerLowerRight = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','beveledin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Title','ShapeFiles',...
    'FontSize',fs0,...
    'HitTest','off',...
    'Position',Positions.CenterContainerLowerRight);

%%%%%%%%
% FarRight Containers 
% FarRight Containers 
%%%%%%%%

LogoContainer = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Visible','off',...
    'Position',Positions.LogoContainer);

FarRightContainer = uipanel(...
    'Parent',Handles.MainFigure,...
    'BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','normalized',...
    'Position',Positions.FarRightContainer);

Handles.InformationPanel = uipanel(...
    'Parent',FarRightContainer,...
    'Title','Information',...
    'BackgroundColor',panelColor,...
    'FontSize',fs0,...
    'bordertype','etchedin',...
    'Position',[.01 .60 .98 .39]);

Handles.VectorOptionsPanel = uipanel(...
    'Parent',FarRightContainer,...
    'Title','Vector Options',...
    'BackgroundColor',panelColor,...
    'FontSize',fs0,...
    'bordertype','etchedin',...
    'Visible','off',...
    'Position',[.01 .60 .98 .39]);

Handles.ControlPanel = uipanel(...
    'Parent',FarRightContainer,...
    'Title','Controls',...
    'BackgroundColor',panelColor,...
    'FontSize',fs0,...
    'bordertype','etchedin',...
    'Visible','off',...
    'Position',[.01 .01 .98 .58]);

% Place Dev Team Logos
 
h=axes('Parent',LogoContainer,'Position',[0.20 0.01 .25 .898]);
im=imread([HOME '/private/RENCI-Logo.tiff']);
axes(h)
image(im(:,:,1:3))
axis off
set(h,'HandleVisibility','off');

h=axes('Parent',LogoContainer,'Position',[0.575 0.01 .36 .898]); 
im=imread([HOME '/private/unc_ims_logo.jpeg']);
axes(h)
image(im)
axis off
set(h,'HandleVisibility','off');
set(LogoContainer,'Visible','on')

%%
%%%%%%%%
% Container Contents
% Container Contents
%%%%%%%%

% MainAxes
Handles.MainAxes=axes(...
    'Parent',MainAxesPanel,...
    'Units','normalized',...
    'Position',[.05 .05 .9 .9],...
    'Box','on',...
    'FontSize',fs0,...
    'Tag','StormSurgeVizMainAxes','Layer','top');


StatusUrlBarContainerContainerContents;
ControlPanelContainerContents;
VectorOptionsPanelContainerContents;
InformationPanelContainerContents;
GraphicOutputControlContainerContents;
BackgroundMapsContainerContents;
SetParameterControls;

%%% only nested functions below here...

%%  SetParameterControls
%%% SetParameterControls
%%% SetParameterControls
    function SetParameterControls
        uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.05 .60 .45 .05],...
            'HorizontalAlignment','left',...
            'FontSize',fs1+1,...
            'FontWeight','bold',...
            'String','Storm Parameters ');
        uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .55 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','RMW :');
       Handles.ParameterControlsParameter(1)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .55 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter1',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(1)));
        
      uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .49 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','Hb :');
       Handles.ParameterControlsParameter(2)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .49 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter2',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(2))); 
        
      uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .43 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','TS :');
       Handles.ParameterControlsParameter(3)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .43 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter3',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(3))); 
        
       uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .37 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','Vmax :');
       Handles.ParameterControlsParameter(4)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .37 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter4',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(4))); 
        
       uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .31 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','Lat1 :');
       Handles.ParameterControlsParameter(5)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .31 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter5',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(5)));
 
       uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .25 .2 .05],...
            'BackGroundColor','w',...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','Lat2 :');
       Handles.ParameterControlsParameter(6)=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .25 .2 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ParameterControlsParameter6',...
            'FontSize',fs2,...
            'String',sprintf('%6.2f',Model.X(6)));
        
      Handles.EvaluateModel=uicontrol(...
            'Parent',Handles.CenterContainerUpper,...
            'Style','pushbutton',...
            'Units','normalized',...
            'Position',[.1 .1 .3 .05],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','EvaluateModel',...
            'FontSize',fs2,...
            'String','Eval Model',...
            'CallBack',@EvaluateModel);
        
    end

%%  StatusUrlBarContainerContainerContents
%%% StatusUrlBarContainerContainerContents
%%% StatusUrlBarContainerContainerContents

    function StatusUrlBarContainerContainerContents
        
        % StatusBar
        % StatusBar
        % StatusBar
        uicontrol(...
            'Parent',StatusUrlBarContainer,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .55 .09 .44],...
            'HorizontalAlignment','right',...
            'FontSize',fs1,...
            'String','Status :');
        Handles.StatusBar=uicontrol(...
            'Parent',StatusUrlBarContainer,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.11 .55 .77 .40],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','StatusBar',...
            'FontSize',fs2,...
            'String','Initializing UI ...');
        
        % UserEnteredText Box
        % UserEnteredText Box
        % UserEnteredText Box
        Handles.UserEnteredText=uicontrol(...
            'Parent',StatusUrlBarContainer,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.89 .55 .10 .40],...
            'HorizontalAlignment','center',...
            'BackGroundColor','w',...
            'Tag','UserEnteredText',...
            'FontSize',fs2,...
            'String','');
        %    'Enable','Inactive',...
        %    'Min',0,'Max',3,...
        % ServerBar
        % ServerBar
        % ServerBar
        uicontrol(...
            'Parent',StatusUrlBarContainer,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .01 .09 .44],...
            'HorizontalAlignment','right',...
            'Tag','ServerInfo',...
            'FontSize',fs1,...
            'String','URL :');
        Handles.ServerInfoString=uicontrol(...
            'Parent',StatusUrlBarContainer,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.11 .01 .88 .48],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','ServerInfoString',...
            'FontSize',fs2,...
            'String',{'<>'},...
            'CallBack',@InstanceUrl);
        
        %    'BackGroundColor','w',...
        %    'HorizontalAlignment','left',...
       
    end

 %%  Graphic Output Control Container Contents
 %%% Graphic Output Control Container Contents
 %%% Graphic Output Control Container Contents
 
    function GraphicOutputControlContainerContents
        
        printobj={'Current Axes';'Current GUI'};
        Handles.GraphicOutputHandlesGroup = uibuttongroup(...
            'Parent',Handles.CenterContainerLowerLeft,...
            'BorderType','etchedin',...
            'FontSize',fs2,...
            'BackGroundColor',panelColor,...
            'Position',[.01 0.1 .96 0.8],...
            'Tag','GraphicOutputHandlesGroup',...
            'SelectionChangeFcn',@SetGraphicOutputType);
        
        for i=1:2
            Handles.GraphicOutputHandles(i)=uicontrol(...
                Handles.GraphicOutputHandlesGroup,...
                'Style','Radiobutton',...
                'String',printobj{i},...
                'Units','normalized',...
                'FontSize',fs2,...
                'Position', [.1 1-0.47*i .9 0.42],...
                'Tag','GraphicOutputHandles');
            
            set(Handles.GraphicOutputHandles(i),'Enable','on');
        end
        
        if ForkAxes,
            set(Handles.GraphicOutputHandles(2),'Enable','off');
        end
        
        Handles.GraphicOutputPrint=uicontrol(...
            Handles.GraphicOutputHandlesGroup,...
            'Style','pushbutton',...
            'String','Print',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.65 0.25 .3 0.5],...
            'CallBack',@GraphicOutputPrint,...
            'Enable','on',...
            'Tag','GraphicOutputPrint');
        
        
        %%% Shape Files
        %%% Shape Files
        %%% Shape Files
        Handles.ExportShapeFilesHandlesGroup = uibuttongroup(...
            'Parent',Handles.CenterContainerLowerRight,...
            'BorderType','etchedin',...
            'FontSize',fs2,...
            'BackGroundColor',panelColor,...
            'Position',[.01 0.1 .98 0.8],...
            'Tag','ExportShapeFilesHandlesGroup',...
            'SelectionChangeFcn',@SetGraphicOutputType);
        
        Handles.ExportShape=uicontrol(...
            Handles.ExportShapeFilesHandlesGroup,...
            'Style','pushbutton',...
            'String','Export',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 0.50 .5 0.45],...
            'CallBack',@ExportShapeFile,...
            'Enable','on',...
            'Tag','ExportShapeFile');
        
     temp=uicontrol(...
            'Parent',Handles.ExportShapeFilesHandlesGroup,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .05 .49 .2],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','',...
            'FontSize',fs3,...
            'String','Shape File Name');
        
        Handles.DefaultShapeFileName=uicontrol(...
            Handles.ExportShapeFilesHandlesGroup,...
            'Style','edit',...
            'String','FileName',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 0.25 .49 0.25],...
            'CallBack',@ExportShapeFile,...
            'Enable','on',...
            'Tag','DefaultShapeFileName');
        
       temp=uicontrol(...
            'Parent',Handles.ExportShapeFilesHandlesGroup,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.51 .05 .4 .2],...
            'HorizontalAlignment','left',...
            'BackGroundColor','w',...
            'Tag','',...
            'FontSize',fs3,...
            'String','Bin Centers');
        
        Handles.ShapeFileBinCenterIncrement=uicontrol(...
            Handles.ExportShapeFilesHandlesGroup,...
            'Style','edit',...
            'String','1',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.51 0.25 .4 0.25],...
            'CallBack',@ExportShapeFile,...
            'Enable','on',...
            'Tag','ShapeFileBinCenterIncrement');
        
        if ~getappdata(Handles.MainFigure,'CanOutputShapeFiles')
            set([Handles.ExportShape Handles.ExportShapeFileName],'Enable','off')
        end
    
    end

%%  Background Maps Container Contents
%%% Background Maps Container Contents
%%% Background Maps Container Contents

    function BackgroundMapsContainerContents
        
        %%% UpdateUI
        %%% UpdateUI
        %%% UpdateUI
        % Handles.UpdateUIButton=uicontrol(...
        %     'Parent',Handles.CenterContainerLower,...
        %     'Style','Pushbutton',...
        %     'String', 'Update UI Contents',...
        %     'Units','normalized',...
        %     'BackGroundColor','w',...
        %     'FontSize',fs0,...
        %     'Position', [.01 .01 Width .1],...
        %     'Tag','UpdateUIButton',...
        %     'Callback', @UpdateUI);
        
        
        if ~UseGoogleMaps,return,end
        
        NVar=5;
        % dy=NVar*.08;
        % y=0.9-NVar*.075;
        
        Handles.BaseMapButtonGroup = uibuttongroup(...
            'Parent',Handles.CenterContainerMiddle,...
            'Title','Map Type ',...
            'FontSize',fs2,...
            'BackGroundColor',panelColor,...
            'Position',[.01 .45 .98 .52],...
            'Tag','BaseMapButtonGroup',...
            'SelectionChangeFcn',@SetBaseMap);
        
        %         dy=.9/(NVar+1);
        buttonnames={'none','roadmap','satellite','terrain','hybrid'};
        ytemp=linspace(4/5,1/5-1/10,5);
        for i=1:NVar
            Handles.BaseMapButtonHandles(i)=uicontrol(...
                'Parent',Handles.BaseMapButtonGroup,...
                'Style','Radiobutton',...
                'String',buttonnames{i},...
                'Units','normalized',...
                'Value',5,...
                'FontSize',fs2,...
                'Position', [.1 ytemp(i) .9 .15],...
                'Tag','BaseMapRadioButton');
        end
        
        uicontrol(...
            'Parent',Handles.CenterContainerMiddle,...
            'Style','text',...
            'String','Transparency',...
            'Units','normalized',...
            'BackGroundColor',panelColor,...
            'FontSize',fs2,...
            'Position', [.01 0.3 .8 .15]);
        
        Handles.TransparencySlider=uicontrol(...
            'Parent',Handles.CenterContainerMiddle,...
            'Style','Slider',...
            'Min', .1,...
            'Max',.99,...
            'Value',.9,...
            'Units','normalized',...
            'BackGroundColor','w',...
            'FontSize',fs1,...
            'Position', [.01 0.2 .8 .15],...
            'Tag','TransparencySlider',...
            'Callback', @SetTransparency);
        
        %     %jShandle=findjobj(Handles.TransparencySlider);
        %     %set(jShandle,'AdjustmentValueChangedCallback',@SetTransparency)
        
        uicontrol(...
            'Parent',Handles.CenterContainerMiddle,...
            'Style', 'text',...
            'String', 'Figure Renderer',...
            'Units','normalized',...
            'BackGroundColor',panelColor,...
            'FontSize',fs2,...
            'Position', [.01 .13 .8 .1]);
        
        % get the current renderer setting
        list={'painter','zbuffer','OpenGL'};
        curren=get(gcf,'Renderer');
        val=find(strcmp(curren,list));
        Handles.FigureRenderer=uicontrol(...
            'Parent',Handles.CenterContainerMiddle,...
            'Style', 'popup',...
            'String', list,...
            'Value',val,...
            'Units','normalized',...
            'BackGroundColor',panelColor,...
            'FontSize',fs2,...
            'Position', [.01 .06 .8 .1],...
            'Tag','SetFigureRendererPopup',...
            'Callback', @SetFigureRenderer);
        
    end

%%  InformationPanelContainerContents
%%% InformationPanelContainerContents
%%% InformationPanelContainerContents
        
    function InformationPanelContainerContents
             
        Width=.48;
        Height=.09;
              
        % ModelName
        % ModelName
        % ModelName
        uicontrol(...
            'Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.01 .9 Width Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Model = ');
        Handles.ModelName=uicontrol(...
            'Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.50 .9 Width Height],...
            'FontSize',fs1,...
            'HorizontalAlignment','left',...
            'Tag','ModelName',...
            'String','N/A');
        
        % StormSurgeGridName
        % StormSurgeGridName
        % StormSurgeGridName
        uicontrol('Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .8 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Model Grid = ');
        Handles.ModelGridName=...
            uicontrol('Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.50 .8 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','ModelGridName',...
            'String','N/A');
        
        % ModelName
        % ModelName
        % ModelName
%         uicontrol(...
%             'Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'BackGroundColor','w',...
%             'Position',[.01 .8 Width Height],...
%             'FontSize',fs2,...
%             'HorizontalAlignment','right',...
%             'String','Model = ');
%         Handles.ModelName=uicontrol(...
%             'Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'BackGroundColor','w',...
%             'Position',[.50 .8 Width Height],...
%             'FontSize',fs2,...
%             'HorizontalAlignment','left',...
%             'Tag','ModelName',...
%             'String','N/A');
        
        % StormNumberName
        % StormNumberName
        % StormNumberName
%         uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'Position',[.01 .7 Width Height],...
%             'BackGroundColor','w',...
%             'FontSize',fs2,...
%             'HorizontalAlignment','right',...
%             'String','Storm Number/Name = ');
%         Handles.StormNumberName=...
%             uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'Position',[.50 .7 Width Height],...
%             'BackGroundColor','w',...
%             'FontSize',fs2,...
%             'HorizontalAlignment','left',...
%             'Tag','StormNumberName',...
%             'String','N/A');
        
        % AdvisoryNumber
        % AdvisoryNumber
        % AdvisoryNumber
%         uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'BackGroundColor','w',...
%             'Position',[.01 .6 Width Height],...
%             'FontSize',fs2,...
%             'HorizontalAlignment','right',...
%             'String','Advisory Number = ');
%         Handles.AdvisoryNumber=...
%             uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'BackGroundColor','w',...
%             'Position',[.50 .6 Width Height],...
%             'FontSize',fs2,...
%             'HorizontalAlignment','left',...
%             'Tag','AdvisoryNumber',...
%             'String','N/A');
%         
 
        
       Handles.ModelGridNums=...
            uicontrol('Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.50 .6 Width Height*1.9],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','ModelGridNums',...
            'String','N/A');
        
        % UnitsString
        % UnitsString
        % UnitsString
        uicontrol('Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .21 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Units = ');
        Handles.UnitsString=...
            uicontrol('Parent',Handles.InformationPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.50 .21 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','UnitsString',...
            'String','N/A');
        
        % TimeOffsetString
        % TimeOffsetString
        % TimeOffsetString
%         uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'Position',[.01 .11 Width Height],...
%             'BackGroundColor','w',...
%             'FontSize',fs2,...
%             'HorizontalAlignment','right',...
%             'String','Time Offset from UTC = ');
%         Handles.TimeOffsetString=...
%             uicontrol('Parent',Handles.InformationPanel,...
%             'Style','text',...
%             'Units','normalized',...
%             'Position',[.50 .11 Width Height],...
%             'BackGroundColor','w',...
%             'FontSize',fs2,...
%             'HorizontalAlignment','left',...
%             'Tag','TimeOffsetString',...
%             'String','0');
        
%         if strcmp(Mode,'Network')
%             Handles.ShowCatalogToggleButton=uicontrol(...
%                 'Parent',Handles.InformationPanel,...
%                 'Style','pushbutton',...
%                 'Units','normalized',...
%                 'Position',[.25 .01 .50 .1],...
%                 'Tag','ShowCatalogToggleButton',...
%                 'FontSize',fs1,...
%                 'String','Show Catalog',...
%                 'CallBack',@DisplayCatalog);
%         else
%             Handles.ShowCatalogToggleButton=uicontrol(...
%                 'Parent',Handles.InformationPanel,...
%                 'Style','pushbutton',...
%                 'Units','normalized',...
%                 'Position',[.25 .01 .50 .1],...
%                 'Tag','ShowCatalogToggleButton',...
%                 'FontSize',fs1,...
%                 'Enable','on',...
%                 'String','Browse File System',...
%                 'CallBack',@BrowseFileSystem);
% %         end
        
        
        % Handles.Field_Maximum=...
        %     uicontrol('Parent',Handles.InformationPanel,...
        %     'Style','text',...
        %     'Units','normalized',...
        %     'Position',[LeftEdge .4 Width Height],...
        %     'Tag','Field_Maximum',...
        %     'HorizontalAlignment','left',...
        %     'String','Maximum = 0');
        %
        % Handles.Field_Minimum=...
        %     uicontrol('Parent',Handles.InformationPanel,...
        %     'Style','text',...
        %     'Units','normalized',...
        %     'Position',[LeftEdge .3 Width Height],...
        %     'HorizontalAlignment','left',...
        %     'Tag','Field_Minimum',...
        %     'String','Minimum = 0');
        
        %              Handles.ModelInitTime=...
        %                  uicontrol('Parent',Handles.InformationPanel,...
        %                     'Style','text',...
        %                     'Units','normalized',...
        %                     'Position',[LeftEdge .2 Width Height],...
        %                     'HorizontalAlignment','left',...
        %                     'Tag','ModelInitTime',...
        %                     'String',sprintf('Model Init = NaN'))
        
        % ForecastStartTime
        % ForecastStartTime
        % ForecastStartTime
        % % uicontrol('Parent',Handles.InformationPanel,...
        % %     'Style','text',...
        % %     'Units','normalized',...
        % %     'Position',[.01 .11 Width Height],...
        % %     'BackGroundColor','w',...
        % %     'FontSize',fs2,...
        % %     'HorizontalAlignment','right',...
        % %     'String',sprintf('Forecast Start = '));
        % % Handles.ForecastStartTime=...
        % %     uicontrol('Parent',Handles.InformationPanel,...
        % %     'Style','text',...
        % %     'Units','normalized',...
        % %     'Position',[.50 .11 Width Height],...
        % %     'BackGroundColor','w',...
        % %     'FontSize',fs2,...
        % %     'HorizontalAlignment','left',...
        % %     'Tag','ForecastStartTime',...
        % %     'String','NaN');
        
        % ForecastEndTime
        % ForecastEndTime
        % ForecastEndTime
        % % uicontrol('Parent',Handles.InformationPanel,...
        % %     'Style','text',...
        % %     'Units','normalized',...
        % %     'FontSize',fs2,...
        % %     'BackGroundColor','w',...
        % %     'Position',[.01 .01 Width Height],...
        % %     'HorizontalAlignment','right',...
        % %     'String','Forecast End   = ');
        % % Handles.ForecastEndTime=...
        % %     uicontrol('Parent',Handles.InformationPanel,...
        % %     'Style','text',...
        % %     'Units','normalized',...
        % %     'FontSize',fs2,...
        % %     'BackGroundColor','w',...
        % %     'Position',[.50 .01 Width Height],...
        % %     'HorizontalAlignment','left',...
        % %     'Tag','ForecastEndTime',...
        % %     'String','NaN');
        
    end

%%  ControlPanelContainerContents
%%% ControlPanelContainerContents
%%% ControlPanelContainerContents

    function ControlPanelContainerContents
        
        Width=.48;
        Height=.07;
        
        % ColormapSetter
        % ColormapSetter
        % ColormapSetter
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .9 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Set Colormap : ');
        
        Handles.ColormapSetter=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style', 'popup',...
            'String', colormaps,...
            'Value',cmapidx,...
            'Units','normalized',...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'Position', [.5 .88 Width/2 Height],...
            'Tag','ColormapSetter',...
            'Callback', @SetColorMap);
        
        Handles.FlipCMap=...
            uicontrol('Parent',Handles.ControlPanel,...
            'Style','checkbox',...
            'Units','normalized',...
            'Position',[.76 .90 Width/2 Height],...
            'FontSize',fs2,...
            'BackGroundColor','w',...
            'Value',0,...
            'HorizontalAlignment','left',...
            'String','Flip CMap',...
            'Tag','FlipCMap',...
            'CallBack',@SetCLims);
        
        % Number of Colors
        % Number of Colors
        % Number of Colors
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'FontSize',fs2,...
            'BackGroundColor','w',...
            'Position',[.01 .8 Width Height],...
            'HorizontalAlignment','right',...
            'String','Number of Colors : ');
        Handles.NCol=...
            uicontrol('Parent',Handles.ControlPanel,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .8 Width/2 Height],...
            'FontSize',fs2,...
            'BackGroundColor','w',...
            'String','32',...
            'HorizontalAlignment','left',...
            'Tag','NCol',...
            'CallBack',@SetCLims);
        
        
        % Color Minimum
        % Color Minimum
        % Color Minimum
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'Position',[.01 .7 Width Height],...
            'String','Color Minimum : ');
        Handles.CMin=...
            uicontrol('Parent',Handles.ControlPanel,...
            'Style','edit',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'Position',[.5 .7 Width/2 Height],...
            'HorizontalAlignment','left',...
            'String','0',...
            'Tag','CMin',...
            'CallBack',@SetCLims);
        
        % Color Maximum
        % Color Maximum
        % Color Maximum
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'Position',[.01 .6 Width Height],...
            'String','Color Maximum : ');
        Handles.CMax=...
            uicontrol('Parent',Handles.ControlPanel,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.5 .6 Width/2 Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'String','1',...
            'Tag','CMax',...
            'CallBack',@SetCLims);
        
        % DepthContours
        % DepthContours
        % DepthContours
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .5 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Depth Contours : ');
        Handles.DepthContours=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style', 'edit',...
            'String', DepthContours,...
            'Units','normalized',...
            'BackGroundColor','w',...
            'HorizontalAlignment','left',...
            'FontSize',fs2,...
            'Position', [.5 .5 Width Height],...
            'Tag','DepthContours',...
            'Callback', @DrawDepthContours);
        
        % AxisLimits
        % AxisLimits
        % AxisLimits
        uicontrol('Parent',Handles.ControlPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .4 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Axis Limits : ');
        Handles.AxisLimits=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style', 'edit',...
            'String',num2str(BoundingBox),...
            'Units','normalized',...
            'BackGroundColor','w',...
            'HorizontalAlignment','left',...
            'FontSize',fs2,...
            'Enable','off',...
            'Position', [.5 .4 Width Height],...
            'Tag','AxisLimits');
        
        
        % ShowMaximum
        % ShowMaximum
        % ShowMaximum
        Handles.ShowMaxButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','pushbutton',...
            'String', {'Show Maximum in View'},...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 .32 Width Height],...
            'Callback', @ShowMaximum,...
            'Tag','ShowMaxButton');
        
        % ShowMapThings
        % ShowMapThings
        % ShowMapThings
        Handles.ShowMapButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', {'Show Roads/Counties'},...
            'Units','normalized',...
            'Position', [0.51 .32 Width Height],...
            'FontSize',fs2,...
            'Callback', @ShowMapThings,...
            'Tag','ShowMapThings');
        
        % ShowMinimum
        % ShowMinimum
        % ShowMinimum
        Handles.ShowMinButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','pushbutton',...
            'String', {'Show Minimum in View'},...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 .25 Width Height],...
            'Callback', @ShowMinimum,...
            'Tag','ShowMinButton');
        
        % FindFieldValue
        % FindFieldValue
        % FindFieldValue
        Handles.FindFieldValueButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', 'Get Field Values',...
            'Units','normalized',...
            'Position', [.51 .25 Width Height],...
            'FontSize',fs2,...
            'Callback', @FindFieldValue,...
            'Tag','FindFieldValueButton');
        
        % ShowTrack
        % ShowTrack
        % ShowTrack
        Handles.ShowTrackButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','pushbutton',...
            'String', 'Show Track',...
            'FontSize',fs2,...
            'Units','normalized',...
            'Position', [.01 .18 Width Height],...
            'Tag','ShowTrackButton',...
            'Callback', @ShowTrack);
        
        % ResetAxes
        % ResetAxes
        % ResetAxes
        Handles.ResetAxesButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','pushbutton',...
            'String', 'Reset Axes',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.51 .18 Width Height],...
            'Tag','ResetAxesButton',...
            'Callback', @ResetAxes);
        
        % Toggle surf edge color
        % Toggle surf edge color
        % Toggle surf edge color
        Handles.ElementsToggleButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', 'Show Elements',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 .11 Width Height],...
            'Tag','ElementsToggleButton',...
            'Callback', @ToggleElements);
        
        % Show Full Domain AXes Extents
        % Show Full Domain AXes Extents
        % Show Full Domain AXes Extents
        Handles.ShowFullDomainToggleButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', 'Show Full Domain',...
            'Units','normalized',...
            'Enable','off',...
            'FontSize',fs2,...
            'Position', [.51 .11 Width Height],...
            'Tag','ShowFullDomainToggleButton',...
            'Callback', @ShowFullDomain);
        
        % FindHydrograph
        % FindHydrograph
        % FindHydrograph
        Handles.HydrographButton=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', 'Plot Hydrographs',...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.51 .04 Width Height],...
            'Tag','HydrographButton',...
            'Callback', @FindHydrograph,...
            'Enable','on');
        
        % Water Level as Inundation
        % Water Level as Inundation
        % Water Level as Inundation
        Handles.WaterLevelAsInundation=uicontrol(...
            'Parent',Handles.ControlPanel,...
            'Style','togglebutton',...
            'String', {'Show Water Level As Inundation'},...
            'Units','normalized',...
            'FontSize',fs2,...
            'Position', [.01 .04 Width Height],...
            'Tag','WaterLevelAsInundation',...
            'Callback', @WaterLevelAsInundation);
             
        set(Handles.ControlPanel,'Visible','on');

        function WaterLevelAsInundation(~,~)
            v=get(Handles.WaterLevelAsInundation,'Value');
            if v
                set(Handles.WaterLevelAsInundation,'String','Turn Off Inundation')
            else
                set(Handles.WaterLevelAsInundation,'String','Turn On Inundation')
            end
        end
        
        
        % if ~UseShapeFiles
        %     set(Handles.ShowMapButton,'Enable','off')
        % end
    end

%%  VectorOptions panel container contents
%%% VectorOptions panel container contents
%%% VectorOptions panel container contents

    function VectorOptionsPanelContainerContents
        
        Width=.33;
        Width2=.17;
        Height=.09;
        
        tbh = findall(Handles.MainFigure,'Type','uitoolbar');
        a=imread('private/vo.png');
        tth = uitoggletool(tbh,'CData',a, 'Separator','on', 'HandleVisibility','off','Enable',Vecs);
        set(tth,'ClickedCallback',@RevealVecOpts)
        set(tth,'TooltipString','Reveal Vector Options')
        
        % Stride
        % Stride
        % Stride
        Height=.12;
        uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.01 .87 Width Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Stride = ');
        Handles.VectorOptionsStride=uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','edit',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.34 .87 Width2 Height],...
            'FontSize',fs1,...
            'HorizontalAlignment','left',...
            'Tag','VectorOptionsStride',...
            'String','1000');
        
        % ScaleFac
        % ScaleFac
        % ScaleFac
        uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.01 .74 Width Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Scale Factor = ');
        Handles.VectorOptionsScaleFactor=uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','edit',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.34 .74 Width2 Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','VectorOptionsScaleFactor',...
            'String','25');
        
        % Color
        % Color
        % Color
        uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','text',...
            'Units','normalized',...
            'Position',[.01 .61 Width Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Color = ');
        Handles.VectorOptionsColor=...
            uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[.34 .61 Width2 Height],...
            'BackGroundColor','w',...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','VectorOptionsColor',...
            'String','k');
        
        % ScaleLabel
        % ScaleLabel
        % ScaleLabel
        uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.01 .48 Width Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Scale Label = ');
        Handles.VectorOptionsScaleLabel=...
            uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','edit',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.34 .48 Width2 Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','VectorOptionsScaleLabel',...
            'String','no scale');
        
        % ScaleOrigin
        % ScaleOrigin
        % ScaleOrigin
        uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','text',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.01 .35 Width Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','right',...
            'String','Scale Origin = ');
        Handles.VectorOptionsScaleOrigin=...
            uicontrol('Parent',Handles.VectorOptionsPanel,...
            'Style','edit',...
            'Units','normalized',...
            'BackGroundColor','w',...
            'Position',[.34 .35 Width2 Height],...
            'FontSize',fs2,...
            'HorizontalAlignment','left',...
            'Tag','VectorOptionsScaleOrigin',...
            'String','NaN NaN');
        
        Handles.VectorOptionsRedrawButton=uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','pushbutton',...
            'Units','normalized',...
            'Position',[.25 .22 .50 .1],...
            'Tag','RedrawVectorsButton',...
            'FontSize',fs1,...
            'String','(Re)Draw Vectors',...
            'CallBack',@RedrawVectors);
        
        Handles.VectorOptionsDeleteButton=uicontrol(...
            'Parent',Handles.VectorOptionsPanel,...
            'Style','pushbutton',...
            'Units','normalized',...
            'Position',[.25 .12 .50 .1],...
            'Tag','DeleteVectorsButton',...
            'FontSize',fs1,...
            'String','Delete Vectors',...
            'CallBack',@DeleteVectors);
        
%         Handles.VectorOptionsOverlayButton=uicontrol(...
%             'Parent',Handles.VectorOptionsPanel,...
%             'Style','checkbox',...
%             'Units','normalized',...
%             'Position',[.25 .02 .50 .1],...
%             'Tag','OverlayVectorsButton',...
%             'FontSize',fs1,...
%             'String','Overlay Vectors',...
%             'CallBack','');
        
        % right side interpolation options
        
        
    end
    fprintf('SSViz++    Done.\n\n')

end